version: "3.9"
services:
    apache:
      build: ./apache
      ports:
        - 8888:80
      volumes:
        - ./html:/var/www/html
    bd:
      image: mariadb
      env_file:
        - .env
      volumes:
        # - ./datos:/var/lib/mysql
        - ./bd/nova.sql:/docker-entrypoint-initdb.d/nova.sql
    adminer:
      image: adminer
      ports:
        - 8082:8080        
    phpmyadmin:
      image: phpmyadmin
      ports:
        - 8081:80
      environment:
        PMA_HOST: bd
        PMA_ARBITRARY: 1     
      
