version: "3.9"
services:
    apache:
      image: httpd
      ports:
        - 8080:80
      volumes:
        - ./html:/usr/local/apache2/htdocs
    bd:
      restart: allways
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: example
      volumes:
        - ./datos:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin
      ports:
        - 8081:80
      environment:
        PMA_HOST: bd
        PMA_ARBITRARY: 1     
      
