version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
    - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    - ./html:/code
    ports:
    - "8088:80"
    depends_on:
        - "php"    
  php:
    build: php
    volumes:
        - ./html:/code
        - ./php/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
        - ./php/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
        - "bd"           
  bd:
    image: mariadb
    env_file:
      - .env
    volumes:
      # - ./datos:/var/lib/mysql
      - ./bd/nova.sql:/docker-entrypoint-initdb.d/nova.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
