version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
    - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    - ./html:/code
    ports:
    - "8088:80"
    depends_on:
        - "php"    
  php:
    image: php:7.4-fpm
    volumes:
        - ./html:/code
        - ./php/php.ini-production:/usr/local/etc/php/php.ini
        # - ./php/php.ini-development:/usr/local/etc/php/php.ini        
    depends_on:
        - "bd"           
  bd:
    image: mariadb
    env_file:
      - .env
    volumes:
      # - ./datos:/var/lib/mysql
      - ./bd/nova.sql:/docker-entrypoint-initdb.d/nova.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
